# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1
      - image: circleci/python:2.7.15


    working_directory: ~/repo

    steps:
      - add_ssh_keys:
          fingerprints:
            - "ae:f0:fd:46:31:14:1a:e2:8b:c5:15:0d:13:aa:14:ff"

      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python3 -m unittest discover

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            coverage run --source CAM2CameraDatabaseAPIClient/ setup.py test

      - run:
          name: code coverage
          command: |
            . venv/bin/activate
            coverage html

      - run:
          name: run linter
          command: |
            . venv/bin/activate
            pylint -j 0 CAM2CameraDatabaseAPIClient

      - store_artifacts:
          path: test-reports
          destination: test-reports

      - store_artifacts:
          path: htmlcov
          destination: code_cov_reports

      - run:
          name: Generate Documentation
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                bash .circleci/generate_docs.sh
            fi
